name: Build Tor archive

on:
  push:
    tags:
      - 'tor-[0-9]*-bundle-[0-9]*'

jobs:
  build-tor:
    runs-on: ubuntu-26.04
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Extract versions
        id: vers
        run: |
          tor_ver=$(echo '${{ github.ref_name }}' | cut -d "-" -f 2)
          bundle_ver=$(echo '${{ github.ref_name }}' | cut -d "-" -f 4)
          echo "tor_ver=$tor_ver" >> "$GITHUB_OUTPUT"
          echo "bundle_ver=$bundle_ver" >> "$GITHUB_OUTPUT"

      - name: Download and extract Tor Expert Bundle archive
        run: |
          mkdir tor-tmp
          curl -fLO https://archive.torproject.org/tor-package-archive/torbrowser/${{ steps.vers.outputs.bundle_ver }}/tor-expert-bundle-windows-x86_64-${{ steps.vers.outputs.bundle_ver }}.tar.gz
          tar xzf tor-expert-bundle-windows-x86_64-${{ steps.vers.outputs.bundle_ver }}.tar.gz -C tor-tmp

      - name: Create Windows distribution
        run: |
          mkdir -p tor/data
          cp tor-tmp/tor/tor.exe tor
          cp tor-tmp/tor/pluggable_transports/lyrebird.exe tor
          cp tor-tmp/data/geoip* tor/data
          cp resources/torrc tor
          cp resources/start-tor.bat tor
          zip -Xr tor-${{ steps.vers.outputs.tor_ver }}-windows-x86_64.zip tor

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          name: Tor ${{ steps.vers.outputs.tor_ver }}
          files: |
            tor-${{ steps.vers.outputs.tor_ver }}-windows-x86_64.zip
